aws_autoscaling_group:
aws_cloudformation_stack:
aws_ecs_cluster:
aws_ebs_snapshot:
aws_ebs_volume:
aws_efs_file_system:
aws_elb:
aws_instance:
aws_launch_configuration:
aws_db_instance:
aws_s3_bucket:
aws_nat_gateway:
aws_eip:
aws_internet_gateway:
  - id: NOT(igw-f0015594)
aws_security_group:
  - id: NOT(sg-b9ff75c3 | sg-07abb62ed7819ff02 | sg-0609a82c80f924a)
aws_subnet:
  - id: NOT(subnet-55223b32 | subnet-245c556d | subnet-bddf0be4)
aws_vpc:
  - id: NOT(vpc-0d2bfc162cddfe3c5|vpc-0e93579f242b04db6)
aws_vpc_endpoint:
aws_network_acl:
  - id: NOT(acl-6fb66809)
aws_route_table:
  - id: NOT(rtb-0cd56d6a)
aws_network_interface:
aws_route53_zone:
  - id: NOT(Z0726841H51TWV79TM8R)
# aws_iam_group:
# aws_iam_instance_profile:
# aws_iam_policy:
# aws_iam_role:
# aws_iam_user:
# aws_key_pair:
# aws_kms_alias:
# aws_kms_key:
# aws_route53_zone:
